/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * testingGUI.java
 *
 * Created on 25.03.2009, 02:48:34
 */

package com.macilias.apps.similaritysearch.algotest.gui;

import com.macilias.apps.similaritysearch.logic.algorithms.lexical.MatrixBasedCompare;

/**
 *
 * @author maciekn
 */
public class testingGUI extends javax.swing.JFrame {
//
//    String str1, str2;
//    MatrixBasedCompare code = new MatrixBasedCompare();
//
//    /** Creates new form testingGUI */
//    public testingGUI() {
//        initComponents();
//    }
//
//    /** This method is called from within the constructor to
//     * initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is
//     * always regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jScrollPane1 = new javax.swing.JScrollPane();
//        jTable1 = new javax.swing.JTable();
//        jScrollPane2 = new javax.swing.JScrollPane();
//        jTable2 = new javax.swing.JTable();
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jTextField1 = new javax.swing.JTextField();
//        jTextField2 = new javax.swing.JTextField();
//        jComboBox3 = new javax.swing.JComboBox();
//        jButton1 = new javax.swing.JButton();
//        jLabel3 = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//
//        jTable1.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null}
//            },
//            new String [] {
//                "Title 1", "Title 2", "Title 3", "Title 4"
//            }
//        ));
//        jScrollPane1.setViewportView(jTable1);
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jTable2.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null}
//            },
//            new String [] {
//                "Title 1", "Title 2", "Title 3", "Title 4"
//            }
//        ));
//        jScrollPane2.setViewportView(jTable2);
//
//        jLabel1.setText("String1");
//
//        jLabel2.setText("String2");
//
//        jTextField1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField1ActionPerformed(evt);
//            }
//        });
//
//        jTextField2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField2ActionPerformed(evt);
//            }
//        });
//
//        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Levenstein", "Neddleman/Wunsch" }));
//
//        jButton1.setText("OK");
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//
//        jLabel3.setText("Rückgabewert");
//
//        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(layout.createSequentialGroup()
//                .add(40, 40, 40)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
//                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
//                        .add(jLabel2)
//                        .add(18, 18, 18)
//                        .add(jTextField2))
//                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
//                        .add(jLabel1)
//                        .add(18, 18, 18)
//                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                    .add(jComboBox3, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .add(18, 18, 18)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(layout.createSequentialGroup()
//                        .add(106, 106, 106)
//                        .add(jLabel4))
//                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
//                        .add(org.jdesktop.layout.GroupLayout.LEADING, jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//                .addContainerGap(430, Short.MAX_VALUE))
//            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(layout.createSequentialGroup()
//                .add(20, 20, 20)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
//                    .add(layout.createSequentialGroup()
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                            .add(jLabel1)
//                            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                            .add(jLabel2)
//                            .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
//                    .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                    .add(jLabel4)
//                    .add(jLabel3)
//                    .add(jComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                .add(15, 15, 15)
//                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_jTextField1ActionPerformed
//
//    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_jTextField2ActionPerformed
//
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        if(jTextField1.getText().equals(""))
//            str1 = "GAATTCAGTTA";
//        else
//            str1 = jTextField1.getText();
//        if(jTextField2.getText().equals(""))
//            str2 = "GGATCGA";
//        else
//            str2 = jTextField2.getText();
//
//        //Setzten des Algorithmen
//        //Levenstein
//        System.out.println("Das ist die Ausgabe: "+jComboBox3.getSelectedItem().toString());
//        if(jComboBox3.getSelectedItem().toString().equals("Levenstein")){
//            code.setAlgo(1);
//        }
//        //Needleman Wunsch
//        if(jComboBox3.getSelectedIndex()==1){
//            code.setAlgo(21);
//        }
//
//
//        jLabel4.setText(String.valueOf(code.compare(str2, str1)));
//        int [][] d = code.getMatrix();
//        String [][] s = new String[str2.length()+1][str1.length()+2];
//        String [] title = new String[str1.length()+2];
//        title[0] = "";
//        title[1] = "";
//        for (int t = 0; t <str1.length();t++){
//            title[t+2] = String.valueOf(str1.charAt(t));
//        }
//        for (int i = 0; i <s.length; i++) {
//              if(i==0)
//                 s[i][0] = " ";
//              else
//                s[i][0] = String.valueOf(str2.charAt(i-1));
//              for (int j = 0; j<s[i].length-1; j++) {
//                   s[i][j+1] = String.valueOf(d[i][j]);
//              }
//        }
//        jTable2.setModel(new javax.swing.table.DefaultTableModel(
//            s, title
//        ));
//    }//GEN-LAST:event_jButton1ActionPerformed
//
//    /**
//    * @param args the command line arguments
//    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new testingGUI().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton jButton1;
//    private javax.swing.JComboBox jComboBox3;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JScrollPane jScrollPane2;
//    private javax.swing.JTable jTable1;
//    private javax.swing.JTable jTable2;
//    private javax.swing.JTextField jTextField1;
//    private javax.swing.JTextField jTextField2;
//    // End of variables declaration//GEN-END:variables

}
